import Head from "next/head";
import Navbar from "~/components/Navbar";
import Banner from "~/components/Banner";
// import { api } from "~/utils/api";
import Signup from "~/components/Signup";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>E-commerce Login | Sign-up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container mx-auto flex flex-col items-center justify-center gap-12 px-4 py-10">
          {/* <p className="text-2xl text-black">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p> */}
          <Signup />
        </div>
      </main>
    </>
  );
}
