[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/inventory"

  [headers.values]
   Access-Control-Allow-Origin = "*"
   Content-value="application/xml; charset=utf-8"